#!/usr/bin/env bash
set -euo pipefail

# Generate .devcontainer/local/.env from SOPS-encrypted secrets + config. Runs
# INSIDE the devcontainer (needs sops + AWS creds for the rg-dev-sops KMS key).
# Invoked from post-create.sh; also safe to run by hand after rotating secrets
# (re-run encrypt-secrets.sh first).
#
# The generated .env is consumed by:
#   - the devcontainer itself via runArgs --env-file (on rebuild)
#   - in-container app builds: `docker compose --env-file .devcontainer/local/.env ...`
#   - the PostHog MCP server (sources this file at launch)
#   - interactive shells (sourced from rc by post-start.sh)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/logger.sh"
export LOG_TAG="build-env"

LOCAL_DIR="$(cd "${SCRIPT_DIR}/../local" && pwd)"
SECRETS_ENC="${LOCAL_DIR}/secrets.enc.json"
DEFAULTS="${LOCAL_DIR}/env.defaults"
OVERRIDES="${LOCAL_DIR}/env.local"
ENV_FILE="${LOCAL_DIR}/.env"

if ! command -v sops >/dev/null 2>&1; then
  log "sops not found; leaving existing ${ENV_FILE} untouched"
  exit 0
fi

if [[ ! -f "$SECRETS_ENC" ]]; then
  log "No ${SECRETS_ENC}; skipping .env generation."
  log "Create it with: cp local/secrets.json.example local/secrets.json && scripts/encrypt-secrets.sh"
  exit 0
fi

log "Decrypting ${SECRETS_ENC}"
secrets_kv="$(sops -d "$SECRETS_ENC" | jq -r 'to_entries[] | select(.key != "sops") | "\(.key)=\(.value)"')"
if [[ -z "$secrets_kv" ]]; then
  echo "Failed to decrypt ${SECRETS_ENC} — check sops + AWS access to the rg-dev-sops KMS key." >&2
  exit 1
fi

umask 077
{
  printf '# AUTO-GENERATED by scripts/build-env.sh — do not edit or commit.\n'
  printf '# Merged from: env.defaults (shared) + secrets.enc.json (SOPS) + env.local\n'
  printf '# (personal, gitignored). Regenerate with build-env.sh; env.local wins.\n\n'
  if [[ -f "$DEFAULTS" ]]; then
    printf '# --- shared non-secret config (from env.defaults) ---\n'
    cat "$DEFAULTS"
    printf '\n'
  else
    log "Warning: ${DEFAULTS} not found; .env will contain secrets only"
  fi
  printf '# --- secrets (decrypted from secrets.enc.json) ---\n'
  printf '%s\n' "$secrets_kv"
  if [[ -f "$OVERRIDES" ]]; then
    printf '\n# --- personal overrides (from env.local) ---\n'
    cat "$OVERRIDES"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

log "Wrote ${ENV_FILE}"
