#!/usr/bin/env bash
set -euo pipefail

# Assemble .devcontainer/local/.env from two plaintext sources:
#   - env.defaults  shared, non-secret team config (committed)
#   - env.local     all secrets — shared team secrets (Twilio, Roark) AND personal
#                   PATs (GitHub, ngrok, Jira, PostHog, npm). Gitignored; copy from
#                   env.local.example and fill in. Applied last, so it wins.
#
# No decryption: shared team secrets are copied once from the team password
# manager into env.local (they are NOT committed). Invoked from post-create.sh;
# also safe to run by hand after editing env.local.
#
# The generated .env is consumed by:
#   - the devcontainer itself via runArgs --env-file (on rebuild)
#   - in-container app builds: `docker compose --env-file .devcontainer/local/.env ...`
#   - the PostHog MCP server (sources this file at launch)
#   - interactive shells (sourced from rc by post-start.sh)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/logger.sh"
export LOG_TAG="build-env"

LOCAL_DIR="$(cd "${SCRIPT_DIR}/../local" && pwd)"
DEFAULTS="${LOCAL_DIR}/env.defaults"
OVERRIDES="${LOCAL_DIR}/env.local"
ENV_FILE="${LOCAL_DIR}/.env"

umask 077
{
  printf '# AUTO-GENERATED by scripts/build-env.sh — do not edit or commit.\n'
  printf '# Merged from: env.defaults (shared, committed) + env.local (secrets,\n'
  printf '# gitignored). env.local is applied last, so it wins on duplicate keys.\n\n'
  if [[ -f "$DEFAULTS" ]]; then
    printf '# --- shared non-secret config (from env.defaults) ---\n'
    cat "$DEFAULTS"
    printf '\n'
  else
    log "Warning: ${DEFAULTS} not found; .env will contain secrets only"
  fi
  if [[ -f "$OVERRIDES" ]]; then
    printf '# --- secrets & personal overrides (from env.local) ---\n'
    cat "$OVERRIDES"
  else
    log "No ${OVERRIDES}; .env will have no secrets."
    log "Create it with: cp local/env.local.example local/env.local  (then fill it in)"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# This script runs as root inside the container. On WSL, files root writes to
# the bind-mounted workspace stay root-owned on the host, which breaks host-side
# tooling (e.g. the devcontainer initializeCommand's touch) and makes .env
# unreadable/uneditable for the host user. Chown the file back to whoever owns
# the workspace mount. Docker Desktop for macOS already remaps ownership, so
# this is effectively a no-op there.
WS_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
ws_owner="$(stat -c '%u:%g' "${WS_ROOT}" 2>/dev/null || true)"
if [[ -n "${ws_owner}" && "${ws_owner}" != "0:0" ]]; then
  chown "${ws_owner}" "$ENV_FILE" 2>/dev/null || true
fi

log "Wrote ${ENV_FILE}"
